### PR TITLE
Update Info

### PR DESCRIPTION
**Pull request by alenzen**
YouTube introduced handle URLs, see https://support.google.com/youtube/answer/6180214
Adding the domain to the Mastodon account makes the account unambiguous.

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@alenzen Thanks!  I was unaware of those formats, and I like them!  I thought this morning that we should also add a line for Desktop.  Could you add:

Desktop:  https://podman-desktop.io/

Between the Website and Documents lines?  Thanks!

**Comment by alenzen** [comment]
> @alenzen Thanks! I was unaware of those formats, and I like them! I thought this morning that we should also add a line for Desktop. Could you add:
> 
> Desktop: https://podman-desktop.io/
> 
> Between the Website and Documents lines? Thanks!

Done.

**Comment by TomSweeneyRedHat** [comment]
TY @alenzen 
LGTM

@benoitf or @slemeur can you just verify that I didn't mess up the URL that I gave @alenzen

**Comment by benoitf** [comment]
@TomSweeneyRedHat I confirm the link is valid 👍 thanks

**Comment by TomSweeneyRedHat** [comment]
Thanks @benoitf !

**Pull request merged**
