### PR TITLE
chore: use ubi/glibc image rather than alpine/libmusl

### PR DESCRIPTION
**Pull request by benoitf**

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Is the ubi-minimal a smaller image than alpine?  I'm all for making the image smaller if so.

**Comment by benoitf** [comment]
it's a multi-staged image so we copy the binary to a scratch image so I would say alpine or ubi9 doesn't really matter on the consumer for the size of the image

but it looks like binary produced on ubi9 is smaller than the one produced by alpine so final size is smaller

```
quay.io/podman/hello                              latest            5cc19cda0756  45 minutes ago  145 kB
localhost/hello.                                  latest            9203310ce1b9  6 seconds ago   142 kB
```

If I compare to hello world of docker, I think there is room for improvement
```
docker.io/library/hello-world                     latest            ee301c921b8a  9 months ago    22.2 kB
```

**Comment by afbjorklund** [comment]
@benoitf 

Seems like something is wrong with your build environment:

```
localhost/hello                redhat         36c9b6960a0d  14 seconds ago      1.7 MB
localhost/hello                alpine         aae615db4fb7  About a minute ago  82.3 kB
```

> If I compare to hello world of docker, I think there is room for improvement

The docker image is handcoded in assembler, rather than in a high level language.

The podman hello was just trying to improve on the initial image, which was 150 MB

* https://github.com/containers/podman/pull/13079

Writing it in C has the benefit that you don't need separate sources for each arch....

**Comment by afbjorklund** [comment]
@TomSweeneyRedHat 

If you absolutely want to make the image smallest possible, you can trade some runtime performance:

```diff
@@ -1,7 +1,8 @@
 FROM docker.io/alpine as builder
-RUN apk add gcc libc-dev
+RUN apk add gcc libc-dev upx
 ADD podman_hello_world.c .
-RUN gcc -O2 -static -o podman_hello_world podman_hello_world.c
+RUN gcc -Os -static -o podman_hello_world podman_hello_world.c
+RUN upx --ultra-brute podman_hello_world
 
 FROM scratch
 LABEL maintainer="Podman Maintainers"
```

```
localhost/hello                brute          62e8064e3709  6 seconds ago   35.2 kB
localhost/hello                alpine         aae615db4fb7  11 minutes ago  82.3 kB
```

Using https://upx.github.io/

----

EDIT: Using `strip` was more effective than `upx`. More portable, as well...

**Pull request merged**
