### PR TITLE
Add a make file for building and running

### LINKED ISSUE #2: Add Makefile
To have the commands from the README in an accessible form.

So that you can just do `make build run`, independent on image.

Like when testing different languages, such as shell or python?

* #4

### PR DESCRIPTION
**Pull request by afbjorklund**
Including an undocumented regular default target,
for building the hello program locally on the host.

`make build`
`make run`

Closes #2

### CODE REVIEW

**Comment by rhatdan** [comment]
What does plain 

```
make
```
Do

**Comment by afbjorklund** [comment]
Plain `make` builds the image, similar to the regular old `all` target (versus `install`)

```console
$ make
podman build -t myhello .
[...]
Successfully tagged localhost/myhello:latest
0b337101d526af92384cd60c7651b662b38530ef347ae1b9f41c908e93b5d7cd
```

It does not `push` or `run` or anything, that is up to the user how they want to use it

I didn't add any fancy dependencies either, like having run depending on the image.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Thanks @afbjorklund

**Pull request merged**
